"""Project 05 -- Damped least-squares IK.

  1. 500 random reachable targets on the 7-DoF arm, six damping settings
  2. the wrist singularity on the 6-DoF arm, driven straight through it
  3. the damping trade-off curve: joint speed bought with tracking error
  4. what happens to the SHAPE of the arm when the solver only cares about pose

Runs in about 90 seconds on a CPU.
"""

import csv
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
for rel in ("01-transform-calculator", "02-urdf-visualizer", "03-forward-kinematics-from-scratch",
            "04-jacobian-from-scratch"):
    sys.path.insert(0, os.path.join(HERE, "..", rel))

import transforms as tf  # noqa: E402
import viz  # noqa: E402
from fk import fk_all  # noqa: E402
from ik import cartesian_lerp, ik, track_path  # noqa: E402
from jacobian import jacobian_analytic, singular_values  # noqa: E402
from plot_style import COLORS, save, use_style  # noqa: E402
from urdf import load_urdf  # noqa: E402

import matplotlib.pyplot as plt  # noqa: E402

OUT = os.path.join(HERE, "outputs")
MODELS = os.path.join(HERE, "..", "02-urdf-visualizer", "models")
os.makedirs(OUT, exist_ok=True)
use_style()
RESULTS = []


def record(name, value, unit=""):
    RESULTS.append({"quantity": name, "value": value, "unit": unit})
    print(f"    {name:<62s} {value:>12.4e} {unit}")


SETTINGS = [
    ("lambda = 0 (plain pseudo-inverse)", dict(lam=0.0)),
    ("lambda = 0.001", dict(lam=1e-3)),
    ("lambda = 0.01", dict(lam=1e-2)),
    ("lambda = 0.05", dict(lam=5e-2)),
    ("lambda = 0.2", dict(lam=2e-1)),
    ("adaptive lambda", dict(adaptive=True)),
    ("lambda = 0.01, clamped to joint limits", dict(lam=1e-2, clamp_limits=True)),
]


# ---------------------------------------------------------------------------
# 1. Convergence over many random targets
# ---------------------------------------------------------------------------
def convergence_study(robot, n=500, seed=0):
    """Targets are generated by forward kinematics, so every one IS reachable.

    That matters: if targets were drawn at random in space, most would be
    unreachable and every solver would 'fail' for a reason that has nothing to
    do with damping.  Generating targets from random joint vectors separates
    'the solver could not find it' from 'there was nothing to find'.
    """
    rng = np.random.default_rng(seed)
    Q_goal = robot.random_q(rng, n)
    Q_start = robot.random_q(rng, n)
    targets = [fk_all(robot, q)["tool0"] for q in Q_goal]

    table = {}
    for label, kw in SETTINGS:
        ok, iters, steps, errs = 0, [], [], []
        for q0, T in zip(Q_start, targets):
            q, info = ik(robot, q0, T, max_iters=200, **kw)
            steps.append(info["max_step"])
            errs.append(info["e_pos"])
            if info["ok"]:
                ok += 1
                iters.append(info["iters"])
        table[label] = {
            "success": ok / n,
            "median_iters": float(np.median(iters)) if iters else float("nan"),
            "median_final_err": float(np.median(errs)),
            "p99_step": float(np.percentile(steps, 99)),
            "max_step": float(np.max(steps)),
        }
        record(f"[{label}] success rate", table[label]["success"])
        record(f"[{label}] median iterations to converge", table[label]["median_iters"])
        record(f"[{label}] 99th-percentile largest joint step", table[label]["p99_step"], "rad")
        record(f"[{label}] largest joint step seen", table[label]["max_step"], "rad")
    return table


def fig_convergence(table, fname):
    labels = list(table)
    fig, axs = plt.subplots(1, 3, figsize=(9.2, 3.0))
    axs[0].barh(labels, [table[k]["success"] for k in labels], color=COLORS[0])
    axs[0].set_xlabel("fraction of 500 targets solved")
    axs[0].set_xlim(0, 1.05)
    axs[0].set_title("did it get there?")
    axs[1].barh(labels, [table[k]["median_iters"] for k in labels], color=COLORS[2])
    axs[1].set_xlabel("median iterations")
    axs[1].set_title("how quickly?")
    axs[1].set_yticklabels([])
    axs[2].barh(labels, [table[k]["max_step"] for k in labels], color=COLORS[1])
    axs[2].set_xscale("log")
    axs[2].set_xlabel("largest single joint step (rad, log)")
    axs[2].set_title("how violently?")
    axs[2].set_yticklabels([])
    axs[2].axvline(np.pi, color="#888888", ls="--", lw=1.0)
    axs[2].text(np.pi * 1.2, -0.4, "half a turn", fontsize=7, color="#666666")
    for ax in axs:
        ax.invert_yaxis()
    fig.suptitle("arm7, 500 reachable targets from random starts: damping costs iterations "
                 "and buys sanity", y=1.04)
    save(fig, f"{OUT}/convergence.png")


# ---------------------------------------------------------------------------
# 2. The wrist singularity
# ---------------------------------------------------------------------------
def singular_path(robot):
    """A straight Cartesian move that drags the wrist through wrist_2 = 0.

    arm6 has a spherical wrist, and its joints 4 and 6 both turn about their
    own z axis.  When wrist_2 (joint 5) is zero those two axes point the same
    way, so between them they can only produce ONE rotation instead of two:
    the Jacobian loses a rank and one direction of tool rotation vanishes.
    """
    q_a = np.array([0.35, 0.55, -1.10, 0.40, 0.85, 0.20])
    q_b = q_a.copy()
    q_b[4] = -0.85  # sweep wrist_2 from +0.85 to -0.85, straight through 0
    T_a, T_b = fk_all(robot, q_a)["tool0"], fk_all(robot, q_b)["tool0"]
    return q_a, cartesian_lerp(T_a, T_b, 401)


def singularity_study(robot, fname):
    q0, path = singular_path(robot)
    dt = 0.005

    # How close does the path actually come to a singular configuration?
    q_mid = q0.copy()
    q_mid[4] = 0.0
    record("smallest singular value AT wrist_2 = 0",
           float(singular_values(jacobian_analytic(robot, q_mid))[-1]))
    record("smallest singular value at wrist_2 = 0.85",
           float(singular_values(jacobian_analytic(robot, q0))[-1]))

    runs = {}
    for label, kw in [("lambda = 0", dict(lam=0.0)),
                      ("lambda = 0.02", dict(lam=2e-2)),
                      ("lambda = 0.1", dict(lam=1e-1)),
                      ("adaptive", dict(adaptive=True))]:
        _, log = track_path(robot, q0, path, dt, **kw)
        runs[label] = log
        record(f"[{label}] peak joint speed", float(log["qd"].max()), "rad/s")
        record(f"[{label}] mean position error along the path", float(log["err_pos"].mean()), "m")
        record(f"[{label}] worst position error along the path", float(log["err_pos"].max()), "m")
        record(f"[{label}] worst orientation error along the path",
               float(np.degrees(log["err_rot"].max())), "deg")

    t = np.arange(len(runs["lambda = 0"]["qd"])) * dt
    fig, axs = plt.subplots(1, 3, figsize=(9.4, 3.0))
    axs[0].plot(t, runs["lambda = 0.02"]["sigma_min"], color="#333333")
    axs[0].set_yscale("log")
    axs[0].set_xlabel("time along the path (s)")
    axs[0].set_ylabel(r"smallest singular value of $J$")
    axs[0].set_title("the arm passes through a singularity")
    for k, (label, log) in enumerate(runs.items()):
        axs[1].plot(t, log["qd"], color=COLORS[k], label=label)
        axs[2].plot(t, log["err_pos"] * 1e3, color=COLORS[k], label=label)
    axs[1].set_yscale("log")
    axs[1].axhline(3.2, color="#888888", ls="--", lw=1.0)
    axs[1].text(1.25, 3.7, "motor limit 3.2 rad/s", fontsize=7, color="#666666")
    axs[1].set_xlabel("time (s)")
    axs[1].set_ylabel("commanded joint speed (rad/s)")
    axs[1].set_title("undamped, the command explodes")
    axs[1].legend(fontsize=7, loc="lower left")
    axs[2].set_yscale("log")
    axs[2].set_xlabel("time (s)")
    axs[2].set_ylabel("tool position error (mm)")
    axs[2].set_title("damping is paid for in accuracy")
    save(fig, f"{OUT}/singularity.png")
    return runs


def fig_tradeoff(robot, fname):
    """Sweep lambda and plot the two things it trades against each other."""
    q0, path = singular_path(robot)
    dt = 0.005
    lams = np.concatenate([[0.0], np.logspace(-4, -0.3, 16)])
    peak, err = [], []
    for lam in lams:
        _, log = track_path(robot, q0, path, dt, lam=lam)
        peak.append(log["qd"].max())
        err.append(log["err_pos"].mean())
    _, log_ad = track_path(robot, q0, path, dt, adaptive=True)

    # Fair comparison: what does FIXED damping cost at the same peak speed?
    peak, err = np.array(peak), np.array(err)
    ad_peak, ad_err = log_ad["qd"].max(), log_ad["err_pos"].mean()
    same_safety = np.argmin(np.abs(peak - ad_peak))
    # NOTE the honest outcome: this ratio comes out near 1.0, i.e. a fixed
    # lambda tuned for THIS path does just as well.  Adaptive damping's real
    # value is that nobody had to tune it -- see the README.
    record("accuracy ratio, adaptive vs the fixed lambda at the same peak speed (>1 = adaptive better)",
           float(err[same_safety] / ad_err), "x")
    record("the fixed lambda that matches adaptive on peak speed", float(lams[same_safety]))
    record("accuracy ratio, adaptive vs a BADLY chosen fixed lambda (the largest swept)",
           float(err[-1] / ad_err), "x")

    fig, ax = plt.subplots(figsize=(6.2, 3.4))
    sc = ax.scatter(peak, err * 1e3, c=np.log10(np.maximum(lams, 1e-5)),
                    cmap="viridis", s=28, zorder=3)
    ax.plot(peak, err * 1e3, color="#BBBBBB", lw=1.0, zorder=2)
    ax.scatter([ad_peak], [ad_err * 1e3], marker="*", s=200,
               color=COLORS[1], zorder=4, label="adaptive damping")
    ax.axvline(3.2, color="#888888", ls="--", lw=1.0)
    ax.text(3.6, err.min() * 1.5e3, "motor limit", fontsize=7, color="#666666", rotation=90)
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("peak commanded joint speed (rad/s)  -- lower is safer")
    ax.set_ylabel("mean tool position error (mm)  -- lower is more accurate")
    ax.set_title("One trade-off curve, and a star that sits ON it:\nadaptive damping matches a hand-tuned lambda without the tuning", fontsize=9)
    fig.colorbar(sc, ax=ax, label=r"$\log_{10}\lambda$")
    ax.legend(fontsize=8, loc="lower left")
    save(fig, f"{OUT}/tradeoff.png")
    record("adaptive: peak joint speed", float(log_ad["qd"].max()), "rad/s")
    record("adaptive: mean position error", float(log_ad["err_pos"].mean() * 1e3), "mm")


# ---------------------------------------------------------------------------
# 3. The solver only cares about the tool
# ---------------------------------------------------------------------------
def posture_drift(robot, n=200, seed=3):
    """Same target, many starts: how different are the arms that get there?

    A 7-joint arm has a whole family of solutions for one tool pose.  Plain IK
    picks whichever member of that family it happened to stumble into, so two
    runs that both 'succeed' can end up in visibly different shapes -- and some
    of them sit hard against a joint limit.  Project 06 is about choosing
    inside that family on purpose.
    """
    rng = np.random.default_rng(seed)
    T = fk_all(robot, robot.random_q(rng))["tool0"]
    sols = []
    for _ in range(n):
        # clamp_limits keeps every solution inside the box the real robot can
        # actually occupy -- without it the solver happily returns joint values
        # of +-100 rad, which are correct arithmetic and impossible hardware.
        q, info = ik(robot, robot.random_q(rng), T, lam=1e-2, max_iters=300, clamp_limits=True)
        if info["ok"]:
            sols.append(q)
    sols = np.array(sols)
    record("solutions found for ONE tool pose", float(len(sols)))
    spread = sols.max(axis=0) - sols.min(axis=0)
    record("widest spread across solutions, over all joints", float(spread.max()), "rad")
    margins = np.array([robot.limit_margin(q).min() for q in sols])
    record("fraction of solutions within 0.1 rad of a joint limit", float((margins < 0.1).mean()))
    record("fraction of solutions AT a joint limit (margin < 1e-6)", float((margins < 1e-6).mean()))

    fig, axs = plt.subplots(1, 2, figsize=(8.4, 3.0))
    for i in range(robot.n):
        axs[0].scatter(np.full(len(sols), i) + rng.normal(0, 0.06, len(sols)), sols[:, i],
                       s=4, alpha=0.35, color=COLORS[0])
        axs[0].plot([i - 0.3, i + 0.3], [robot.lower[i]] * 2, color=COLORS[1], lw=2)
        axs[0].plot([i - 0.3, i + 0.3], [robot.upper[i]] * 2, color=COLORS[1], lw=2)
    axs[0].set_xticks(range(robot.n))
    axs[0].set_xticklabels(robot.joint_names, rotation=35, ha="right", fontsize=7)
    axs[0].set_ylabel("joint value (rad)")
    axs[0].set_title(f"{len(sols)} joint vectors, ONE tool pose\n(orange = joint limits)", fontsize=9)
    axs[1].hist(margins, bins=30, color=COLORS[0])
    axs[1].axvline(0.1, color=COLORS[1], ls="--")
    axs[1].set_xlabel("distance to the nearest joint limit (rad)")
    axs[1].set_ylabel("solutions")
    axs[1].set_title("plain IK does not care how close it parks\nto a limit", fontsize=9)
    save(fig, f"{OUT}/posture_spread.png")
    return sols


def fig_solution_gallery(robot, sols, fname, k=5):
    fig = plt.figure(figsize=(2.0 * k, 2.2))
    idx = np.linspace(0, len(sols) - 1, k).astype(int)
    for i, s in enumerate(idx):
        ax = fig.add_subplot(1, k, i + 1, projection="3d")
        viz.draw_ground(ax, radius=0.45)
        viz.draw_robot(ax, robot, fk_all(robot, sols[s]), show_frames=["tool0"], frame_scale=0.10)
        viz.style_3d(ax, None, radius=0.60, center=(0, 0, 0.46), ticks=False, azim=-58)
    fig.suptitle("Five different arms, one identical tool pose (to 1e-5 m)", y=0.99)
    fig.subplots_adjust(wspace=-0.2, top=0.93, bottom=-0.06, left=0.0, right=1.0)
    save(fig, f"{OUT}/solution_gallery.png")


def main():
    arm7 = load_urdf(os.path.join(MODELS, "arm7.urdf"))
    arm6 = load_urdf(os.path.join(MODELS, "arm6.urdf"))

    print("\n[1] 500 random reachable targets on arm7")
    table = convergence_study(arm7)
    fig_convergence(table, "convergence.png")

    print("\n[2] driving arm6 through its wrist singularity")
    singularity_study(arm6, "singularity.png")

    print("\n[3] the damping trade-off curve")
    fig_tradeoff(arm6, "tradeoff.png")

    print("\n[4] one pose, many arms")
    sols = posture_drift(arm7)
    fig_solution_gallery(arm7, sols, "solution_gallery.png")

    with open(f"{OUT}/results.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["quantity", "value", "unit"], lineterminator="\n")
        w.writeheader()
        for r in RESULTS:
            w.writerow(r)
    print(f"  wrote {OUT}/results.csv")


if __name__ == "__main__":
    main()
