/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post126, git sha1 b5170e139) */

(* top =  1  *)
(* src = "tt_designs.py:97" *)
(* generator = "Amaranth" *)
module tt_um_binneuron(uio_in, clk, rst, uo_out, ui_in);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [7:0] \$1 ;
  wire [4:0] \$10 ;
  wire [5:0] \$11 ;
  wire \$12 ;
  reg [7:0] \$13 ;
  reg [7:0] \$14 ;
  wire [1:0] \$2 ;
  wire [2:0] \$3 ;
  wire [3:0] \$4 ;
  wire [4:0] \$5 ;
  wire [5:0] \$6 ;
  wire [6:0] \$7 ;
  wire [7:0] \$8 ;
  wire [8:0] \$9 ;
  (* src = "tt_designs.py:107" *)
  wire [7:0] agree;
  (* src = "_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "tt_designs.py:94" *)
  wire [7:0] dot;
  (* src = "tt_designs.py:109" *)
  wire [3:0] pop;
  (* src = "_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "tt_designs.py:99" *)
  reg [7:0] thresh = 8'h00;
  (* src = "tt_designs.py:90" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "tt_designs.py:91" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "tt_designs.py:92" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* src = "tt_designs.py:93" *)
  reg [7:0] weights = 8'h00;
  assign \$1  = ui_in ^ (* src = "tt_designs.py:108" *) weights;
  assign agree = ~ (* src = "tt_designs.py:108" *) \$1 ;
  assign \$2  = 1'h0 + (* src = "tt_designs.py:110" *) agree[0];
  assign \$3  = \$2  + (* src = "tt_designs.py:110" *) agree[1];
  assign \$4  = \$3  + (* src = "tt_designs.py:110" *) agree[2];
  assign \$5  = \$4  + (* src = "tt_designs.py:110" *) agree[3];
  assign \$6  = \$5  + (* src = "tt_designs.py:110" *) agree[4];
  assign \$7  = \$6  + (* src = "tt_designs.py:110" *) agree[5];
  assign \$8  = \$7  + (* src = "tt_designs.py:110" *) agree[6];
  assign \$9  = \$8  + (* src = "tt_designs.py:110" *) agree[7];
  assign \$11  = \$10  - (* src = "tt_designs.py:111" *) 4'h8;
  assign \$12  = $signed(\$11 ) >= (* src = "tt_designs.py:114" *) $signed(thresh);
  (* src = "tt_designs.py:93" *)
  always @(posedge clk)
    weights <= \$13 ;
  (* src = "tt_designs.py:99" *)
  always @(posedge clk)
    thresh <= \$14 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$13  = weights;
    if (uio_in[0]) begin
      \$13  = ui_in;
    end
    if (rst) begin
      \$13  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$14  = thresh;
    if (uio_in[1]) begin
      \$14  = ui_in;
    end
    if (rst) begin
      \$14  = 8'h00;
    end
  end
  assign pop = \$9 [3:0];
  assign dot = { \$11 [5], \$11 [5], \$11  };
  assign uo_out = { \$12 , \$11 [5], \$11  };
  assign \$10  = { \$9 [3:0], 1'h0 };
endmodule
