/* Generated by Amaranth Yosys 0.50 (PyPI ver 0.50.0.0.post126, git sha1 b5170e139) */

(* top =  1  *)
(* src = "tt_designs.py:44" *)
(* generator = "Amaranth" *)
module tt_um_mac8(uio_in, clk, rst, uo_out, ui_in);
  reg \$auto$verilog_backend.cc:2355:dump_module$1  = 0;
  wire [15:0] \$1 ;
  wire [24:0] \$2 ;
  reg [23:0] \$3 ;
  reg [7:0] \$4 ;
  (* src = "tt_designs.py:45" *)
  reg [7:0] a = 8'h00;
  (* src = "tt_designs.py:41" *)
  reg [23:0] acc = 24'h000000;
  (* src = "tt_designs.py:51" *)
  wire [7:0] b;
  (* src = "_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "tt_designs.py:51" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "tt_designs.py:39" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "tt_designs.py:40" *)
  output [7:0] uo_out;
  reg [7:0] uo_out;
  (* src = "tt_designs.py:45" *)
  always @(posedge clk)
    a <= \$4 ;
  assign \$1  = $signed(a) * (* src = "tt_designs.py:57" *) $signed(ui_in);
  assign \$2  = $signed(acc) + (* src = "tt_designs.py:57" *) $signed(\$1 );
  (* src = "tt_designs.py:41" *)
  always @(posedge clk)
    acc <= \$3 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$4  = a;
    if (uio_in[0]) begin
      \$4  = ui_in;
    end
    if (rst) begin
      \$4  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    casez (uio_in[5:4])
      2'h0:
          uo_out = acc[7:0];
      2'h1:
          uo_out = acc[15:8];
      default:
          uo_out = acc[23:16];
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2355:dump_module$1 ) begin end
    \$3  = acc;
    if (uio_in[2]) begin
      \$3  = 24'h000000;
    end else if (uio_in[1]) begin
      \$3  = \$2 [23:0];
    end
    if (rst) begin
      \$3  = 24'h000000;
    end
  end
  assign b = ui_in;
endmodule
