"""Motion models and the target that refuses to obey them.

Two linear models appear here.  Both describe an object in a plane; they differ
only in what they assume is constant.

  CV -- constant velocity.  State [x, y, vx, vy].  "The target keeps going."
  CA -- constant acceleration.  State [x, y, vx, vy, ax, ay].  "The target keeps
        turning/speeding up the way it currently is."

Neither is true.  A real aircraft flies straight, then banks, then flies
straight.  The whole of experiment 5 is about what each model costs you on the
parts of the flight it was not designed for.
"""

import numpy as np


# ------------------------------------------------------------------ CV model
def cv_matrices(dt, q):
    """Return (F, Q, H, dim) for a constant-velocity model in 2-D.

    The process noise is the *discretized white-noise acceleration* model: we
    pretend an unknown acceleration of strength q rattles the target between
    samples, and integrate its effect on position and velocity.  That gives the
    dt^3/3, dt^2/2, dt block below -- the same block that appeared in project
    24's two-state filter, because it is the same physics one dimension down.
    """
    F1 = np.array([[1.0, dt], [0.0, 1.0]])
    Q1 = q * np.array([[dt ** 3 / 3.0, dt ** 2 / 2.0],
                       [dt ** 2 / 2.0, dt]])
    # Interleave x and y.  State order is [x, y, vx, vy], so the 2x2 blocks are
    # scattered rather than contiguous -- write it out rather than use kron, so
    # the ordering is visible and cannot silently transpose.
    F = np.eye(4)
    F[0, 2] = F[1, 3] = dt
    Q = np.zeros((4, 4))
    for i, j in ((0, 2), (1, 3)):
        Q[i, i] = Q1[0, 0]; Q[i, j] = Q1[0, 1]
        Q[j, i] = Q1[1, 0]; Q[j, j] = Q1[1, 1]
    H = np.zeros((2, 4))
    H[0, 0] = H[1, 1] = 1.0          # we see position only
    return F, Q, H, 4


# ------------------------------------------------------------------ CA model
def ca_matrices(dt, q):
    """Return (F, Q, H, dim) for a constant-acceleration model in 2-D.

    State [x, y, vx, vy, ax, ay].  Now q is a *jerk* strength: how fast the
    acceleration itself is allowed to wander.
    """
    F = np.eye(6)
    F[0, 2] = F[1, 3] = dt
    F[2, 4] = F[3, 5] = dt
    F[0, 4] = F[1, 5] = 0.5 * dt ** 2
    Q1 = q * np.array([[dt ** 5 / 20.0, dt ** 4 / 8.0, dt ** 3 / 6.0],
                       [dt ** 4 / 8.0, dt ** 3 / 3.0, dt ** 2 / 2.0],
                       [dt ** 3 / 6.0, dt ** 2 / 2.0, dt]])
    Q = np.zeros((6, 6))
    for a, b, c in ((0, 2, 4), (1, 3, 5)):
        idx = (a, b, c)
        for r in range(3):
            for s in range(3):
                Q[idx[r], idx[s]] = Q1[r, s]
    H = np.zeros((2, 6))
    H[0, 0] = H[1, 1] = 1.0
    return F, Q, H, 6


# ------------------------------------------------------------- the true path
def straight_turn_straight(n, dt, speed=20.0, turn_rate=np.deg2rad(6.0),
                           t_turn=(20.0, 35.0)):
    """A target that flies straight, banks through a coordinated turn, then
    flies straight again.  Returns (positions, velocities, accelerations).

    This shape is deliberate: it contains a long stretch where the constant-
    velocity model is exactly right and a short stretch where it is exactly
    wrong.  A tracker tuned to win on one loses on the other, and experiment 5
    measures the size of that trade.
    """
    t = np.arange(n) * dt
    pos = np.zeros((n, 2))
    vel = np.zeros((n, 2))
    acc = np.zeros((n, 2))
    heading = 0.0
    p = np.array([0.0, 0.0])
    for k in range(n):
        turning = t_turn[0] <= t[k] < t_turn[1]
        w = turn_rate if turning else 0.0
        v = speed * np.array([np.cos(heading), np.sin(heading)])
        a = speed * w * np.array([-np.sin(heading), np.cos(heading)])
        pos[k] = p
        vel[k] = v
        acc[k] = a
        p = p + v * dt + 0.5 * a * dt ** 2
        heading += w * dt
    return pos, vel, acc


def constant_velocity_path(n, dt, speed=20.0):
    t = (np.arange(n) * dt)[:, None]
    v = np.array([[speed * np.cos(0.4), speed * np.sin(0.4)]])
    return t * v, np.repeat(v, n, axis=0), np.zeros((n, 2))


def random_walk_path(n, dt, q, rng, speed=20.0):
    """A target that drifts the way the CV model says targets drift.

    This one matters.  If the truth is a perfectly straight line, the best
    process noise is always q = 0 and every tuning sweep runs off the left edge
    of the plot -- the answer is "believe the model completely", which teaches
    nothing.  Here the truth is generated by the SAME stochastic model the
    filter assumes, with a known strength q, so the sweep has an interior
    optimum and we can check whether the filter finds the q that made the data.

    The velocity is nudged each step by a Gaussian of variance q*dt (that is
    what "spectral density q" means: variance accumulates at q per second), and
    the position picks up the matching half-step term.
    """
    pos = np.zeros((n, 2))
    vel = np.zeros((n, 2))
    v = speed * np.array([np.cos(0.4), np.sin(0.4)])
    p = np.zeros(2)
    for k in range(n):
        pos[k] = p
        vel[k] = v
        a = np.sqrt(q / dt) * rng.standard_normal(2)     # per-step acceleration
        p = p + v * dt + 0.5 * a * dt ** 2
        v = v + a * dt
    return pos, vel, np.zeros((n, 2))
