"""URDF -> MJCF migration: the audit, the mesh generator, and the model builder.

The point of this file is that a "conversion" is not a file-format translation.
MuJoCo will happily read ``hobby_arm.urdf`` as it stands -- and give you a
robot whose forearm has the rotational inertia of a flywheel, because that is
what the file says.  The numbers have to be fixed, and each fix is a separate
decision you can turn on and off here so that ``run.py`` can price it.

Everything is built from ONE parameter table (``LINKS``) plus a set of defect
flags.  ``build_mjcf(set())`` is the clean robot; ``build_mjcf({"inertia"})``
is the clean robot with exactly one thing wrong.
"""

import math
import os
import xml.etree.ElementTree as ET

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
MESH_DIR = os.path.join(HERE, "meshes")

# ---------------------------------------------------------------------------
# The truth table.  These are the numbers a careful person would put in the
# file; the URDF's *geometry* already agrees with them, only its *inertia*
# does not.
# ---------------------------------------------------------------------------
LINKS = [
    dict(name="link1", shape="box", size=(0.06, 0.06, 0.10), mass=0.50,
         com=(0.0, 0.0, 0.05), axis="z",
         joint="j_yaw", jaxis=(0, 0, 1), jpos=(0, 0, 0.02),
         range=(-3.14, 3.14), armature=0.010),
    dict(name="link2", shape="cyl", size=(0.020, 0.25), mass=0.60,
         com=(0.125, 0.0, 0.0), axis="x",
         joint="j_shoulder", jaxis=(0, 1, 0), jpos=(0, 0, 0.10),
         range=(-2.0, 2.0), armature=0.010),
    dict(name="link3", shape="cyl", size=(0.018, 0.20), mass=0.40,
         com=(0.10, 0.0, 0.0), axis="x",
         joint="j_elbow", jaxis=(0, 1, 0), jpos=(0.25, 0, 0),
         range=(-2.6, 2.6), armature=0.006),
]

TOOL_MASS = 0.05
TOOL_POS = (0.20, 0.0, 0.0)      # in link3's frame
DAMPING = 0.05                   # N m s / rad, viscous
FRICTIONLOSS = 0.02              # N m, dry (Coulomb) friction

# every defect this project can inject, one at a time
DEFECTS = ("inertia", "com", "mesh", "damping", "armature", "limits")


# ---------------------------------------------------------------------------
# rigid-body inertia of the two primitive shapes, about their own COM
# ---------------------------------------------------------------------------
def principal_inertia(link):
    """Diagonal inertia (Ixx, Iyy, Izz) of a link about its centre of mass.

    A box a*b*c has I = m/12 * (b^2+c^2, a^2+c^2, a^2+b^2).
    A solid cylinder of radius r and length L has m*r^2/2 about its own axis
    and m*(3r^2 + L^2)/12 about the two axes across it.
    """
    m = link["mass"]
    if link["shape"] == "box":
        a, b, c = link["size"]
        return np.array([m * (b * b + c * c), m * (a * a + c * c),
                         m * (a * a + b * b)]) / 12.0
    r, L = link["size"]
    along = m * r * r / 2.0
    across = m * (3 * r * r + L * L) / 12.0
    out = {"x": [along, across, across],
           "y": [across, along, across],
           "z": [across, across, along]}[link["axis"]]
    return np.array(out, dtype=float)


def merged_link3():
    """link3 plus the welded tool mass, as one rigid body.

    The tool sits on link3's x axis, so the combined inertia stays diagonal:
    a point mass at distance d on the x axis adds 0 to Ixx and m*d^2 to the
    other two.  We still have to move the centre of mass.
    """
    L = LINKS[2]
    m1, c1 = L["mass"], np.array(L["com"])
    m2, c2 = TOOL_MASS, np.array(TOOL_POS)
    M = m1 + m2
    com = (m1 * c1 + m2 * c2) / M
    # link3's own inertia; the tool is a point mass and has none of its own
    I = principal_inertia(L)
    # parallel-axis theorem: moving an inertia off the centre of mass by d
    # adds m*d^2 about the axes perpendicular to d
    for m, c in ((m1, c1), (m2, c2)):
        d = c - com
        I = I + m * np.array([d[1] ** 2 + d[2] ** 2,
                              d[0] ** 2 + d[2] ** 2,
                              d[0] ** 2 + d[1] ** 2])
    return M, com, I


# ---------------------------------------------------------------------------
# meshes: what a "collision mesh" costs when it is really a decoration
# ---------------------------------------------------------------------------
def _obj(path, verts, faces):
    with open(path, "w") as f:
        f.write("# generated by migrate.py\n")
        for v in verts:
            f.write("v %.6f %.6f %.6f\n" % tuple(v))
        for a, b, c in faces:
            f.write("f %d %d %d\n" % (a + 1, b + 1, c + 1))


def _cylinder_mesh(r, L, axis, seg):
    """A finely tessellated cylinder -- the kind a CAD exporter emits."""
    verts, faces = [], []
    for i in range(seg):
        t = 2 * math.pi * i / seg
        y, z = r * math.cos(t), r * math.sin(t)
        for s in (-L / 2, L / 2):
            v = {"x": (s, y, z), "y": (y, s, z), "z": (y, z, s)}[axis]
            verts.append(v)
    for i in range(seg):
        a, b = 2 * i, 2 * i + 1
        c, d = 2 * ((i + 1) % seg), 2 * ((i + 1) % seg) + 1
        faces += [(a, b, d), (a, d, c)]
    return verts, faces


def _box_mesh(size, seg=8):
    """A box subdivided seg x seg per face -- geometrically a box, but with
    hundreds of vertices for the collision engine to chew on."""
    a, b, c = (s / 2 for s in size)
    verts, faces = [], []
    for sgn, ax in ((1, 0), (-1, 0), (1, 1), (-1, 1), (1, 2), (-1, 2)):
        u = np.linspace(-1, 1, seg + 1)
        base = len(verts)
        for i in u:
            for j in u:
                p = [0.0, 0.0, 0.0]
                p[ax] = sgn * (a, b, c)[ax]
                o1, o2 = [k for k in range(3) if k != ax]
                p[o1] = i * (a, b, c)[o1]
                p[o2] = j * (a, b, c)[o2]
                verts.append(tuple(p))
        n = seg + 1
        for i in range(seg):
            for j in range(seg):
                p0 = base + i * n + j
                faces += [(p0, p0 + 1, p0 + n), (p0 + 1, p0 + n + 1, p0 + n)]
    return verts, faces


def make_meshes(seg=192):
    os.makedirs(MESH_DIR, exist_ok=True)
    v, f = _box_mesh(LINKS[0]["size"])
    _obj(os.path.join(MESH_DIR, "link1.obj"), v, f)
    for L in LINKS[1:]:
        r, ln = L["size"]
        v, f = _cylinder_mesh(r, ln, L["axis"], seg)
        _obj(os.path.join(MESH_DIR, L["name"] + ".obj"), v, f)
    return {L["name"]: len(_read_v(os.path.join(MESH_DIR, L["name"] + ".obj")))
            for L in LINKS}


def _read_v(path):
    return [l for l in open(path) if l.startswith("v ")]


# ---------------------------------------------------------------------------
# the auditor
# ---------------------------------------------------------------------------
def audit(urdf_path):
    """Read a URDF and report everything that will bite you in simulation."""
    root = ET.parse(urdf_path).getroot()
    findings = []

    for link in root.findall("link"):
        name = link.get("name")
        inert = link.find("inertial")
        if inert is None:
            findings.append(("FATAL", name, "no <inertial> at all"))
            continue
        mass = float(inert.find("mass").get("value"))
        it = inert.find("inertia")
        diag = [float(it.get(k)) for k in ("ixx", "iyy", "izz")]
        off = [float(it.get(k)) for k in ("ixy", "ixz", "iyz")]

        if mass <= 0:
            findings.append(("WARN", name, "mass = 0 (fatal if a joint moves it)"))
        if all(abs(d - 1.0) < 1e-9 for d in diag) and not any(off):
            findings.append(("FATAL", name,
                             "inertia is the identity matrix -- CAD placeholder"))
        elif mass > 0:
            # triangle inequality: no real body can have Ixx + Iyy < Izz
            a, b, c = sorted(diag)
            if a + b < c - 1e-12:
                findings.append(("FATAL", name, "inertia violates A+B>=C"))
        if inert.find("origin") is None and mass > 0:
            findings.append(("FATAL", name,
                             "<inertial> has no <origin>: COM sits on the joint"))
        for col in link.findall("collision"):
            if col.find("geometry/mesh") is not None:
                findings.append(("WARN", name,
                                 "collision uses a mesh, not a primitive"))

    for j in root.findall("joint"):
        name, jt = j.get("name"), j.get("type")
        if jt in ("revolute", "prismatic", "continuous"):
            if j.find("dynamics") is None:
                findings.append(("WARN", name, "no <dynamics>: zero damping/friction"))
            if jt == "continuous":
                findings.append(("WARN", name, "type=continuous: no joint limits"))
            findings.append(("INFO", name,
                             "URDF cannot express rotor inertia (armature)"))
        if jt == "fixed":
            findings.append(("INFO", name,
                             "fixed joint: MuJoCo will weld the child away"))
    return findings


# ---------------------------------------------------------------------------
# the MJCF builder
# ---------------------------------------------------------------------------
def _geom(link, use_mesh):
    """Collision geometry for one link: a primitive, or the decorative mesh."""
    if use_mesh:
        return '<geom type="mesh" mesh="%s" pos="%s" density="0" rgba="0.7 0.7 0.8 1"/>' % (
            link["name"], " ".join("%g" % c for c in link["com"]))
    if link["shape"] == "box":
        return '<geom type="box" size="%g %g %g" pos="%s" density="0" rgba="0.7 0.7 0.8 1"/>' % (
            link["size"][0] / 2, link["size"][1] / 2, link["size"][2] / 2,
            " ".join("%g" % c for c in link["com"]))
    r, L = link["size"]
    half = {"x": (L / 2, 0, 0), "y": (0, L / 2, 0), "z": (0, 0, L / 2)}[link["axis"]]
    c = np.array(link["com"])
    a, b = c - half, c + half
    return ('<geom type="capsule" size="%g" fromto="%s %s" density="0" '
            'rgba="0.7 0.7 0.8 1"/>') % (
        r, " ".join("%g" % x for x in a), " ".join("%g" % x for x in b))


def build_mjcf(defects=(), floor=False, timestep=0.002, integrator="implicitfast",
               floor_z=-0.25):
    """Emit an MJCF string.  ``defects`` is any subset of ``DEFECTS``."""
    d = set(defects)
    parts = ['<mujoco model="arm">',
             '  <compiler angle="radian" meshdir="meshes"/>',
             '  <option timestep="%g" integrator="%s"/>' % (timestep, integrator),
             '  <asset>']
    for L in LINKS:
        parts.append('    <mesh name="%s" file="%s.obj"/>' % (L["name"], L["name"]))
    parts.append('  </asset>')
    parts.append('  <worldbody>')
    if floor:
        parts.append('    <geom name="floor" type="plane" size="2 2 0.1" '
                     'pos="0 0 %g"/>' % floor_z)
    parts.append('    <body name="base_link" pos="0 0 0">')
    parts.append('      <geom type="cylinder" size="0.05 0.02" density="0"/>')

    indent = "      "
    close = []
    for i, L in enumerate(LINKS):
        if i == 2:
            mass, com, I = merged_link3()
        else:
            mass, com, I = L["mass"], np.array(L["com"]), principal_inertia(L)
        if "inertia" in d:
            I = np.ones(3)                     # the CAD placeholder
        if "com" in d:
            com = np.zeros(3)                  # <inertial> without an <origin>

        parts.append('%s<body name="%s" pos="%s">' % (
            indent, L["name"], " ".join("%g" % x for x in L["jpos"])))
        jt = ['<joint name="%s" type="hinge" axis="%s"' % (
            L["joint"], " ".join("%d" % a for a in L["jaxis"]))]
        if "limits" not in d:
            jt.append('range="%g %g" limited="true"' % L["range"])
        if "damping" not in d:
            jt.append('damping="%g" frictionloss="%g"' % (DAMPING, FRICTIONLOSS))
        if "armature" not in d:
            jt.append('armature="%g"' % L["armature"])
        parts.append('%s  %s/>' % (indent, " ".join(jt)))
        parts.append('%s  <inertial pos="%s" mass="%g" diaginertia="%s"/>' % (
            indent, " ".join("%.9g" % x for x in com), mass,
            " ".join("%.9g" % x for x in I)))
        parts.append('%s  %s' % (indent, _geom(L, "mesh" in d)))
        close.append(indent)
        indent += "  "

    # the tool frame survives as a zero-geom child body + a site
    parts.append('%s<body name="tool_link" pos="%s">' % (
        indent, " ".join("%g" % x for x in TOOL_POS)))
    parts.append('%s  <site name="tcp" size="0.008" rgba="1 0.3 0.1 1"/>' % indent)
    parts.append('%s</body>' % indent)
    for ind in reversed(close):
        parts.append('%s</body>' % ind)
    parts.append('    </body>')
    parts.append('  </worldbody>')
    parts.append('  <actuator>')
    for L in LINKS:
        parts.append('    <motor joint="%s" ctrlrange="-20 20"/>' % L["joint"])
    parts.append('  </actuator>')
    parts.append('</mujoco>')
    return "\n".join(parts)


if __name__ == "__main__":
    counts = make_meshes()
    print("meshes written to meshes/ :", counts)
    print()
    for sev, where, what in audit(os.path.join(HERE, "hobby_arm.urdf")):
        print("%-6s %-14s %s" % (sev, where, what))
    print()
    open(os.path.join(HERE, "arm_clean.mjcf"), "w").write(build_mjcf())
    print("wrote arm_clean.mjcf")
